version: '3.8'

services:
  dev-env:
    build: .
    tty: true
    volumes:
      - type: bind
        source: .
        target: /go/src/interface-realize
      - type: volume
        source: packages
        target: /go/pkg/
      - type: bind
        source: ~/.ssh
        target: /root/.ssh
        read_only: true

    working_dir: /go/src/interface-realize

volumes:
  packages:
