version: '3.8'

services:
  builder:
    build: .
    volumes:
      - type: bind
        source: .
        target: /go/src/interface-realize
    working_dir: /go/src/interface-realize
    command: make build

  tester:
    build: .
    volumes:
      - type: bind
        source: .
        target: /go/src/interface-realize
    working_dir: /go/src/interface-realize
    command: make test

  develop:
    build: .
    volumes:
      - type: bind
        source: .
        target: /go/src/interface-realize
    working_dir: /go/src/interface-realize
    tty: true
